#import "../components/PastProjects.gql"
#import "../components/StudentQuotes.gql"
#import "../components/Sponsors.gql"
#import "../components/ThemeNotifier.gql"

query IndexQuery ($endDate: CmsDateTime!) {
  cms {
    events(
      limit: 1,
      order: startsAt_ASC,
      where: {
        program: { webname: "virtual" }
        endsAt_gte: $endDate,
      }
    ) {
      items {
        title
        startsAt
        endsAt
        participantRoleId
        notice {
          json
        }
        ...ThemeNotifier
        kickoffVideo {
          url
        }
      }
    }

    ...Sponsors
    ...StudentQuotes


      faqs (
        where: {
          program: {webname:"virtual"},
          audience_contains_all: ["Student"]
        },
        order: [featured_DESC, sys_firstPublishedAt_ASC],
        limit: 6,
      ) {
        items {
          title
          answer {
            json
          }
        }
      }
    }

    ...PastProjects
}
