query PostersQuery ($endDate: CmsDateTime!) {
  cms {
    events(limit: 1,
      order:startsAt_DESC
      where: {
        program: {webname: "virtual"},
        endsAt_gte: $endDate,
      }) {
      items {
        title
        posters {
          items {
            url
            fileName
          }
        }
        program {
          posters {
            items {
              url
              fileName
            }
          }
        }
      }
    }
  }
}